### ISSUE TITLE
how to generate BinData（result in mongodb）second parameter？

### ISSUE THREAD

**Issue by whiteFlower666** [agoston/spring-data-mongodb-encrypt#64]
for example:
origin key String:  "earth is round "
----after encrypt------
encrypted String : "gJNJl3Eij5hX/dJeVgJ/eATIQqahYfUxg89wtKjZL1zxL5h4PTqGqjjn4HbBXbAibw=="

result in mongodb：
"secretString" : BinData(0,"gJNJl3Eij5hX/dJeVgJ/eATIQqahYfUxg89wtKjZL1zxL5h4PTqGqjjn4HbBXbAibw==")

how to genarate encrypted String directly ？

my test code is below:
--------
        byte[] secretKey = Base64.getDecoder().decode("hqHKBLV83LpCqzKpf8OvutbCs+O5wX5BPu3btWpEvXA=");
        CryptVault cryptVault =
            new CryptVault().with256BitAesCbcPkcs5PaddingAnd128BitSaltKey(0, secretKey).withDefaultKeyVersion(0);
        String phoneNumber = "earth is round ";
        byte[] encrypt = cryptVault.encrypt(phoneNumber.getBytes());
        String encodeToString = Base64.getEncoder().encodeToString(encrypt);
        System.out.println("---encrypt---");
        System.out.println(encodeToString);
---------

but encodeToString is not equal to secretString what I want.

**Comment by agoston** [comment]
Mind that BinData is in fact, stored as a binary blob. Mongo client would base64 it for you, so that it can be displayed, but it still is just a binary blob.

CryptVault would also return a byte[] for the very same reason.

The `spring-data-mongodb-encrypt` library uses `CryptVault` to encrypt/decrypt data on-the-fly.

If you want to see an example, `PolymorphismSystemTest.checkReflectiveEncryption()` has an example of testing for raw binary encrypted data as read from DB directly. I suggest you open this in Intellij IDEA CE, set a breakpoint in this test, and try to step through line by line to get an idea of how data looks like in memory.
